gorilla/websocket

client.go
client_server_test.go

Enable the `Host:` header to be customized in a `Dialer.Dial` call.
This is needed to implement websocket proxies.
Please see discussion in #63.

Allow separate specification of http/dial Hosts

---

conn.go

Taking a look at the documentation of the [Close Frame](https://tools.ietf.org/html/rfc6455#section-5.5.1) in the WebSocket RFC it mentions the following:
> When sending a Close frame in response, the endpoint typically echos the status code it received.
This PR does just that, when a Close Frame is received, it echoes it to the other endpoint.

Close Frame Response

---

.gitignore
examples/chat/conn.go
examples/chat/hub.go
examples/chat/main.go

At the moment it's a little hard to figure out what's going on when a bunch of variables are `h`, `c`, `m`, and so on. This is pretty normal shorthand Go users, but in example code it's quicker to understand if shorthand is avoided.
edit: Happy to refactor the names to something else if you prefer. `mainHub` especially I don't love.

Example code clarity improvement

---

conn.go

When set custom handler we must reply to ping message with pong manually. 
This allow us to get the original handler and chain the handlers.

Add Ping/Pong handler Getter functions

---

README.md

Reflect recent update to golang.org/x/net/websocket that introduced limit of received messages.

Update README to reflect change of Go sub-repo websocket feature

---

client.go
client_server_test.go

This allows users to add a cookie jar the same way it can be done for the `http.Client` of the `net/http` package
Example:
```
import (
"net"
"net/http"
"net/http/cookiejar"
"github.com/gorilla/websocket"
)
func main () {
var jar http.CookieJar
jar, _ = cookiejar.New(nil)
Url := "http://example.com"
Dialer := websocket.Dialer{Jar: jar}
header := http.Header{}
ws, res, err := Dialer.Dial(Url, header)
...
}
```

add cookie jar to dialer

---

examples/chat/README.md
examples/chat/client.go

- Discuss concurrency and message coalescing in the README.
- Add comments to client.go explaining how concurrency requirements are
met.
- Prevent developers from calling the Client.write method from outside
of the writePump goroutine by removing the method. The code is now
inlined in Client.writPump.

Improve chat example

---

compression_test.go

This is to help in investigating #203 
Output on my machine:
```
BenchmarkWriteNoCompression-4            3000000               503 ns/op              48 B/op          1 allocs/op
BenchmarkWriteWithCompression-4            30000             41481 ns/op             123 B/op          3 allocs/op
```
Investingating only `BenchmarkWriteWithCompression`, here is cpu profile output:
```
(pprof) top 10 --cum
1.14s of 1.55s total (73.55%)
Showing top 10 nodes out of 67 (cum >= 0.95s)
flat  flat%   sum%        cum   cum%
0     0%     0%      1.54s 99.35%  github.com/FZambia/websocket.(*Conn).WriteMessage
0     0%     0%      1.54s 99.35%  github.com/FZambia/websocket.BenchmarkWriteWithCompression
0     0%     0%      1.54s 99.35%  runtime.goexit
0     0%     0%      1.54s 99.35% …
```

benchmarks for write with compression enabled/disabled

---

compression.go
compression_test.go

Currently SetCompressionLevel panics: `index out of range`.

fix flate write pool size to work with best compression

---

doc.go

I thought code snippet catches attention well in general, and it's nice to have it for `EnableCompression`.
Maybe it's just me, but I tried to add `EnableWriteCompression(true)` to my code first before reading the whole paragraph. Then I realized `EnableCompression` is the one necessary while `enableWriteCompression` is actually true by default if `EnableCompression` is on.

Add code snippet for EnableCompression in doc.go

---

examples/chat/main.go
examples/command/main.go
examples/filewatch/main.go

From the documentation on [html/template](https://golang.org/pkg/html/template/):
> Package template (html/template) implements data-driven templates for generating HTML output safe against code injection. It provides the same interface as package text/template and should be used instead of text/template whenever the output is HTML.
Since some of the files in the examples were parsing HTML with `text/template`, I've updated them to the recommended `html/template`. It is important to make this update because the examples in this repo are likely used as reference material by beginners thus should exhibit best practices.

Change text/template to html/template in the examples

---

client.go

At moment client always tries to use compression when `EnableCompression` is on in `Dialer` - even if server does not want to negotiate it.

Enable client compression based on response header

---

doc.go
server.go

The documentation regarding which Upgrade method/function is deprecated was a bit confusing. I updated the language to make it a bit clearer.

distinguish Upgrader.Upgrade from Upgrade

---

examples/echo/server.go

The opening `<html>` tag is missing.

Add missing html tag in example/echo

---

client.go
client_server_test.go
client_test.go

Fixes #290. Tested OK with our Proxy impl.
I've also removed TestParseURL().

Replace parseURL() with net/url.Parse() (#290)

---

client_server_test.go
conn_test.go
util_test.go

Simplify and fix spelling errors in test files

---

doc.go

I noticed the example is actually wrong as the same block both calls `return` with no parameter and `return err`. I think it would be better to allow the code to be used directly. I added calls to log.Println as it was used on the other example as it might be more useful for newcomers to see error messages.

More consistent error handling in doc

---

server.go
server_test.go

According to [RFC 4343](https://tools.ietf.org/html/rfc4343) DNS hostnames should be case insensitive. This modifies the `checkSameOrigin()` helper to compare hosts without case sensitivity.

origin host check should be case insensitive

---

client_server_test.go
server.go

Change the error text for bad handshake errors from
websocket: not a websocket handshake:
to:
websocket: the client is not using the websocket protocol:
The new text should be more helpful to developers who do not know or
understand the details of the protocol.

Improve bad handshake error text

---

examples/chat/client.go

It's useless and only gives more work to the GC.

examples/chat/client.go: avoid allocating []byte{} for PingMessage

---

examples/chat/client.go

This error is expected (Safari closes connections without sending a close
frame).
Fixes #323

Don't log 1006 error in chat example

---

conn.go

The documentation sometimes used the term "frame" when referring to
single frame control messages.  Use the term "message" for consistency
in the documentation and to hide a detail that most application
programmers do not need to know about.

Replace "frame" with "message" in documentation

---

doc.go
server.go

Remove the example code to disable origin checks from the documentation.
I am concerned that developers are copying the code without
understanding the security implications of the code. Most applications
should not use this code.
Change the bad origin error message to mention Upgrader.CheckOrigin

Improve check origin documentation

---

examples/echo/client.go

Use existing `done` channel to signal that reader is done instead of closing the connection.
Fix #347

Simplify echo example client

---

client_server_test.go
examples/autobahn/server.go
examples/chat/main.go
examples/command/main.go
examples/filewatch/main.go
server.go

Go provides http status codes as const variables.
[Godoc](https://godoc.org/net/http#pkg-constants)

Modify http status code to variable

---

client.go

If `Sec-WebSocket-Protocol` is set in Headers, set it in capitalize instead of canonical for servers that depend on it.

Sec-WebSocket-Protocol is capitalize instead of canonical

---

client.go
server.go

Change the subprotocol and extension header names to match the case used
in RFC examples. Other headers names already match the case used in the
examples.
Although the headers names in the handshake are case insensitive, some
libraries expect the exact case used in the RFC examples. This change
allows the package to interoperate with those broken libraries.

Modify headers to match case used in RFC examples

---

client.go
compression_test.go
conn.go
conn_broadcast_test.go
conn_test.go
json_test.go
prepared_test.go
server.go
server_test.go

This PR proposes an API for write buffer pooling #9. If the API is
approved, I'll complete the implementation.
This proposed API has a typesafe API for the buffer pool and adds a
helper function to make it easy to use sync.Pool.

Add write buffer pooling

---

.travis.yml
client.go
client_server_test.go
trace.go
trace_17.go

In order to enable httptrace, you need to add a context to the request.
With this modification, you can add the context to the request if you give the context to the new DialWithContext.

Add context in the Dialer

---

.travis.yml
client.go
conn_broadcast_test.go
mask_test.go
prepared.go
server.go
server_test.go
util.go

- Use short variable declarations where possible.
- Remove unnecessary build tags after move to Go 1.7 min version.
- Simplify composite literals.
- Remove unused fields (err in PerparedMessage)

Simplify code

---

client.go
client_server_test.go

Follows best practice and [context](https://golang.org/pkg/context/) documentation:
> The Context should be the first parameter, typically named ctx
Similarly, `NetDialContext` already does this.

Move context to first parameter in DialContext

---

client_server_test.go

Add table driven test for handling of host in request URL, request
header and TLS server name. In addition to testing various uses of host
names, this test also confirms that host names are handled the same as
the net/http client.
The new table driven test replaces TestDialTLS, TestDialTLSNoverify,
TestDialTLSBadCert and TestHostHeader.
Eliminate duplicated code for constructing root CA.

Add comprehensive host test

---

util.go
util_test.go

Because the net/http server removes \r\n from multi-line header values,
there's no need to to check for \r or \n when skipping whitespace in
headers (see https://godoc.org/net/textproto#Reader.ReadMIMEHeader).
Given this fact, the whitespace test can be simplified to b == ' ' || b
== '\t'.  There's no need for the isSpaceOctet bit field in octetTypes.
The isTokenOctet bit field is the only bit field remaining after the removal of
isSpaceOctet.  Simplify the code by replacing the isTokenOctet bit test
in octetTypes with an array of booleans called isTokenOctet.
Declare isTokenOctet as a composite literal instead of constructing it
at runtime.
Add documentation to core functions for parsing HTTP headers.

Improve header parsing code

---

client.go
conn.go
server.go

Add "in bytes" to sizes in documentation

---

join.go
join_test.go

Fixes #441.
Issue #441 specified a message separator. This PR has a message terminator.   A message terminator can be read immediately following a message.  A message separator cannot be read until the start of the next message.  The message terminator is more useful when the reader is scanning to the terminator before performing some action.

Add JoinMessages

---

conn.go
conn_test.go
go.mod

This fix addresses a potential denial-of-service (DoS) vector that can cause an integer overflow in the presence of malicious WebSocket frames.
The fix adds additional checks against the remaining bytes on a connection, as well as a test to prevent regression.
Credit to [Max Justicz](https://justi.cz/) for discovering and reporting this, as well as providing a robust PoC and review.

Read Limit Fix

---

client_server_test.go

1. minor typo "optiona" -> "optional"

minor typo

---

example_test.go

Fixes a couple of small typos in the example test docs.

Fix a couple of small typos

---

conn.go
prepared.go

Use empty struct instead of boolean for write protection
on connection.
*Motivation*
1. Using empty struct for signaling is more idiomatic
compared to booleans because users might wonder
what happens on false or true. Empty struct removes
this problem.
2. There is also a side benefit of occupying less memory
but it should be negligible in this case.

Use empty struct to protect writing

---

examples/echo/server.go

The `print` function adds text as `innerHTML`, but  the text is not HTML.  Use `textContent` instead.

echo example: handle received messages as text, not HTML

---

conn.go

Fixes #
1. Fixed duration order consistency when multiplying number by time unit in conn.go

Duration order consistency when multiplying number by time unit

---

go.sum

Prep for v1.4.2.
* Ran `go mod tidy` - an empty `go.sum` is valid here and intended as we don't have non-stdlib dependencies.

build: clean up go.sum

---

client.go
client_server_test.go

The values of the `Upgrade` and `Connection` response headers can
contain multiple tokens, for example
Connection: upgrade, keep-alive
The WebSocket RFC describes the checking of these as follows:
2. If the response lacks an |Upgrade| header field or the |Upgrade|
header field contains a value that is not an ASCII case-
insensitive match for the value "websocket", the client MUST
_Fail the WebSocket Connection_.
3. If the response lacks a |Connection| header field or the
|Connection| header field doesn't contain a token that is an
ASCII case-insensitive match for the value "Upgrade", the client
MUST _Fail the WebSocket Connection_.
It is careful to note "contains a value", "contains a token".
Previously, the client would reject with "bad handshake" if the header
doesn't contain exactly …

Fix how the client checks for presence of Upgrade: websocket, Connection: upgrade

---

client.go
client_server_test.go
examples/autobahn/server.go
examples/chat/main.go
examples/command/main.go
examples/filewatch/main.go
proxy.go
server.go
server_test.go

Go provides http method codes as const variables.

Modify http Method String Literal to Variable

---

conn_broadcast_test.go

This pull request fixes broadcast benchmarks.
Before:
```
BenchmarkBroadcast/NoCompression-4         	     159	   7825192 ns/op	      22 B/op	       0 allocs/op
BenchmarkBroadcast/WithCompression-4       	      67	  17692579 ns/op	 1192272 B/op	   30004 allocs/op
BenchmarkBroadcast/NoCompressionPrepared-4 	     136	   9620360 ns/op	     224 B/op	       1 allocs/op
BenchmarkBroadcast/WithCompressionPrepared-4         	     139	   9190567 ns/op	    8922 B/op	       2 allocs/op
```
After:
```
BenchmarkBroadcast/NoCompression-4                   148           8806814 ns/op              43 B/op          1 allocs/op
BenchmarkBroadcast/Compression-4                      64          17525206 ns/op         1157741 B/op      30002 allocs/op
BenchmarkBroadcast/NoCompressionPrepared-4           136 …
```

Fix broadcast benchmarks

---

client.go
client_server_test.go

Fixes issue: https://github.com/gorilla/websocket/issues/745
With the previous interface, NetDial and NetDialContext were used for
both TLS and non-TLS TCP connections, and afterwards TLSClientConfig was
used to do the TLS handshake.
While this API works for most cases, it prevents from using more advance
authentication methods during the TLS handshake, as this is out of the
control of the user.
This commits introduces another a new dial method, NetDialTLSContext,
which is used when dialing for TLS/TCP. The code then assumes that the
handshake is done there and TLSClientConfig is not used.
This API change is fully backwards compatible and it better aligns with
net/http.Transport API, which has these two dial flavors. See:
https://pkg.go.dev/net/http#Transport

Dialer: add optional method NetDialTLSContext

---

server.go
util.go
util_test.go

Fixes issue: #617
Added the following two fixes
- Check that Sec-websocket-key is encoded as base64
- Check that Sec-Websocket-Key is encoded from 16 bytes long
[RFC6455](https://datatracker.ietf.org/doc/html/rfc6455#section-4.2.1) states the following:
> A |Sec-WebSocket-Key| header field with a base64-encoded value that, when decoded, is 16 bytes in length.

Add check for Sec-WebSocket-Key header

---

conn.go
conn_test.go
server_test.go

Fixes #766
1. Changed the method name `UnderlyingConn` to `NetConn` and marked `UnderlyingConn` as deprecated
2. Changed the test name to `TestDeprecatedUnderlyingConn`
3. Added new test `TestNetConn` to test `NetConn` method

Changed the method name UnderlyingConn to NetConn

---

.circleci/config.yml

Fixes #792
all within `.circleci/config.yml`:
1. point the image field to the new image URL.
2. fix the working directory (the old working directory no longer works against the new image).
3. drop go versions that are no longer supported + add 1.18
> PS: Make sure your PR includes/updates tests! If you need help with this part, just ask!

remove all versions < 1.16 and add 1.18

---

README.md
examples/bufferpool/client.go
examples/bufferpool/server.go

1. Add an example that uses the write buffer pool
The loop process of the websocket connection is inner the http handler at existing examples， This usage will cause the 8k buffer(4k read buffer + 4k write buffer) allocated  by net.http can't be GC(Observed by heap profiling, see picture below) . The purpose of saving memory is not achieved even if the WriteBufferPool is used. 
In example bufferpool, server process websocket connection in a new goroutine, and the goroutine created by the net.http will exit, then the 8k buffer will be GC.

Correct way to save memory using write buffer pool and freeing net.http default buffers

---

README.md
examples/chat/README.md

Update README.md, replace master to main

---

client.go
proxy.go

Use status code constant

---

conn.go
conn_test.go

Noticed a change in default close handler from 1.5.0 to 1.5.1
1.5.1 Now returns the error from `WriteControl` with `CloseMessage` type. However this results in ErrCloseSent returned if the connection initiated the close handshake. This is normally correct as the connection should not be able to write after a close handshake is initiated, except when calling the close handler. in that case nil should be returned so that `advanceFrame()` can return the actual close message.

conn.go: default close handler should not return ErrCloseSent.

---

examples/filewatch/main.go

`ioutil.ReadFile` is Deprecated, As of Go 1.16, this function simply calls [os.ReadFile].

fix: replace ioutil.readfile with os.readfile

---

server.go

😅  Every time I use `gorilla/websocket`, I need to look at the source code and find the default size for readBufferSize and writeBufferSize.
I think the default value should be written in the comment.

fix: add comment for the readBufferSize and writeBufferSize

---

compression.go
conn.go

A recent check in causes `NextReader()` and `beginMessage()` to emit noisy, non-actionable messages that fill up application logs. This PR restores the previous approach of ignoring reader/writer close errors. This should address https://github.com/gorilla/websocket/issues/852.
- Closes #852

Remove noisy printf in NextReader() and beginMessage()

---

examples/autobahn/server.go

As of Go 1.16, ioutil.ReadAll was deprecated.
https://pkg.go.dev/io/ioutil

docs(echoreadall): fix function echoReadAll comment

---

server.go
server_test.go

Since go1.20 [http.ResponseController](https://pkg.go.dev/net/http#ResponseController) is a preferable tool for connection hijacking. It allows to use custom response writer interceptors with `Unwrap()  http.ResponseWriter` method.

Upgrader.Upgrade: use http.ResposnseController

---

conn.go

The 666c197 added an error handling in `SetCloseHandler()` and peer stops getting `CloseError` when network issue like `write: broken pipe` happens because the close handle returns the error.
Hence this patch changes to skip network error handling.

Do not handle network error in `SetCloseHandler()`

---

conn.go
conn_test.go

In most cases, we do not write concurrently to the same client, and the `gorilla` library limits the concurrency, when `gorilla` detect write data concurrently, throw panic ?  In the  addition, creating and stopping a timer is not a simple action. 😁
So, we can get the lock first and if we can't get it, we can create a timer. 😁

perf: reduce timer in write_control

---

conn.go
conn_test.go
examples/echo/client.go
examples/echo/server.go

The `messageType` and `message` can be retrieved using the readMessage method, i want to convert mt int to string by  `FormatMessageType` ? 😁 
```go
var upgrader = websocket.Upgrader{} // use default options
func echo(w http.ResponseWriter, r *http.Request) {
c, err := upgrader.Upgrade(w, r, nil)
if err != nil {
log.Print("upgrade:", err)
return
}
defer c.Close()
for {
mt, message, err := c.ReadMessage()
if err != nil {
log.Println("read:", err)
break
}
log.Printf("recv: %s, type: %s", message, websocket.FormatMessageType(mt))  // 😁
err = c.WriteMessage(mt, message)
if err != nil {
log.Println("write:", err)
break
}
}
}
```

feat: format message type

---

conn.go
conn_test.go

Since this change https://github.com/gorilla/websocket/pull/840/files#diff-4f427d2b022907c552328e63f137561f6de92396d7a6e8f6c2ea1bcf0db52654L190-R197 we can no longer determinate if the errors coming from ReadMessage() are net.ErrClosed for example
Hardcoding the error message is not great option because it may vary from OS to OS and system locale
- Related Issue # https://github.com/gorilla/websocket/issues/877
- Closes # https://github.com/gorilla/websocket/issues/877

Remove hideTempErr to allow downstream users to check for errors like net.ErrClosed

---

conn.go
conn_test.go

A zero value for the Conn.WriteControl deadline specifies no timeout, but the feature was implemented as a very long timeout (1000 hours). This PR updates the code to use no timeout when the deadline is zero.
See the discussion in #895 for more details.
- Closes #895

Do not timeout when WriteControl deadline is zero

---

.github/workflows/verify.yml
.golangci.yml

As `gosec` catches the Error Handling loopholes, silencing the errchecks by `golangci-lint`.
- Will help in eliminating duplicate verification failures

Excludes errchecks linter

---

client.go
client_server_test.go
compression.go
compression_test.go
conn.go
proxy.go
server.go

With #840 debug messages were printed to stderr, as this wasn't very application friendly. With this, the noise in the logs will be reduced, without impacting error handling.
- Closes #880

Return errors instead of printing to logs

---

server.go
server_test.go

Use http.ResponseController to hijack the connection.
- Original PR #871

Use http.ResponseController

---

server.go
server_test.go

Changed the order of subprotocol selection to prefer client one.
Original PR #823

Fixes subprotocol selection (aligning with rfc6455) 

---

proxy.go

- [x ] Bug Fix
- Related Issue #928
- Closes #875

Silence false positive lint warning in proxy code

---

conn.go
prepared_test.go

Silence a lint warning by using crypto/rand instead of math/rand to generate frame masks.
- Closes #

Use crypto/rand for mask key

---

client_server_test.go
server.go
server_test.go

Use Reader.Size() (add in Go 1.10) to get the bufio.Reader's size instead of examining the return value from Reader.Peek.
Use Writer.AvailableBuffer() (added in Go 1.18) to get the bufio.Writer's buffer instead of observing the buffer in the underlying writer.
Allow client to send data before the handshake is complete. Previously, Upgrader.Upgrade rudely closed the connection.
- Closes #642

Improve bufio handling in Upgrader.Upgrade

---

client.go
client_server_test.go
compression.go
compression_test.go
conn.go
conn_broadcast_test.go
conn_test.go
join_test.go
prepared_test.go
server.go

The package ignored errors from net.Conn Set*Deadline in a few places. Update the package to return these errors to the caller.
Ignore all other errors reported by errcheck. These errors are safe to ignore because
- The function is making a best effort to cleanup while handling another error.
- The function call is guaranteed to succeed.
- The error is ignored in a test.
- Closes #

Handle errcheck warnings

---

client.go
client_proxy_server_test.go
proxy.go

* Implements missing HTTPS Proxy functionality.
* Adds client/proxy/server unit tests.
- Closes https://github.com/gorilla/websocket/issues/739
- Closes https://github.com/gorilla/websocket/issues/794
- Previous Unit Test Coverage: 83.6%
- Current Unit Test Coverage: 84.2%
```
$ go test -race -cover
PASS
coverage: 84.2% of statements
ok  	github.com/gorilla/websocket	4.103s
```

Implements missing HTTPS proxy functionality
