- examples/chat/conn.go
Not important but just happened to notice it.
> Small typo fix in comment

- client.go
- client_server_test.go
Firstly the intent of this pull request is to enable websocket clients to traverse proxy servers using the standard environment variables in line with the golang http package.
The reason I am submitting this patch is one of the upstream consumers of this library currently doesn't work when run within an isolated network environment (see https://github.com/aws/amazon-ecs-agent/issues/23).
I have tried to incorporate a simple and easily overridable API along with test coverage for my additions.
> Proxy support for websocket clients.

- client.go
- client_server_test.go
This pull request adds proxy authorization support for websocket clients. 
For example, if the `HTTP_PROXY` env is set to `http://username:password@proxy.example.com`, websocket clients send `Proxy-Authorization: Basic dXNlcm5hbWU6cGFzc3dvcmQ=` in `CONNECT` requests (Note: `base64("username:password") == "dXNlcm5hbWU6cGFzc3dvcmQ"`).
> Support proxy authorization for websocket client

- .travis.yml
@kisielk I don't have a commit bit on this repo.
> Update .travis.yml to build Go 1.6

- examples/chat/README.md
- examples/chat/client.go
Specify correct function name in Chat example README.
> Fix documentation

- util.go
- util_test.go
Compare request header tokens with ASCII case folding per the WebSocket
RFC.
> Compare request header tokens with ASCII case folding

- conn.go
- conn_test.go
- mask.go
- util.go
The changes are compatible with older versions of gofmt.
> Update with gofmt on tip

- conn.go
Return empty message for CloseNoStatusReceived. This status indicates
that the message is empty, so make it so. Because it's illegal to send
CloseNoStatusReceived, this change should not break a correct
application.
> Handle no status in FormatCloseMessage

- conn.go
> Improve control message handler doc

- server.go
> Improve server subprotocol documentation

- client.go
Sorry for the dumbest PR ever, but this tiny addition of a period changes the formatting of this sentence from a header to a regular paragraph in godoc.
> Fix formatting problem in the docs.

- README.md
- examples/autobahn/README.md
> Updated autobahn test suite URL

- go.mod
- go.sum
> Add support for go-module

- server.go
> fix typos in server.go

- examples/chat/home.html
1. input autofocus
i'm too lazy to move my mouse
> input autofocus

- examples/echo/server.go
for better example
1. output element height resize to 70vh
2. scroll to bottom on every 'print'
> improve echo example

- client.go
Signed-off-by: Ye Sijun <junnplus@gmail.com>
Fixes https://github.com/gorilla/websocket/issues/693
1. check error before GotConn for trace
> PS: Make sure your PR includes/updates tests! If you need help with this part, just ask!
> check err before GotConn for trace

- examples/command/main.go
> fix: lint example code

- prepared_test.go
- Related Issue #924
- Closes #924 
- References #920 
> Fixes broken random value generation

- .circleci/config.yml
- go.mod
Update go.mod and CI to Go version 1.20.
- Closes #
> Set min Go version to 1.20

- client.go
- client_server_test.go
- compression_test.go
- conn.go
- conn_broadcast_test.go
- conn_test.go
- examples/autobahn/server.go
- examples/filewatch/main.go
> Update for deprecated ioutil package

- client_server_test.go
Tests must not call *testing.T methods after the test function returns. Use a sync.WaitGroup to ensure that server handler functions complete before tests return.
None
> Improve client/server tests

- README.md
- examples/chat/README.md
> Update README.md, replace master to main

- client_server_test.go
- server.go
Return 426 status on missing upgrade header.
- Closes #915
> Return 426 status on missing upgrade header
